# Generated by Django 4.2.16 on 2026-03-18 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_trade', models.CharField(choices=[('bricklaying', 'Bricklaying & Masonry'), ('carpentry', 'Carpentry & Joinery'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical Installation'), ('roofing', 'Roofing'), ('painting', 'Painting & Finishing'), ('tiling', 'Tiling & Flooring'), ('welding', 'Welding & Fabrication'), ('plastering', 'Plastering'), ('landscaping', 'Landscaping & Paving'), ('glazing', 'Glazing & Windows'), ('general', 'General Construction')], max_length=40)),
                ('secondary_trades', models.JSONField(blank=True, default=list)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True, help_text='Comma-separated certificates')),
                ('service_areas', models.CharField(blank=True, help_text='Areas served in Zimbabwe', max_length=250)),
                ('is_museyamwa', models.BooleanField(default=False, help_text='Small informal/independent artisan (Museyamwa)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artisans/profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artisan Profile',
                'ordering': ['-average_rating', '-completed_jobs'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='artisans/portfolio/')),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate value in USD', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='artisans.artisanprofile')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='artisans.artisanprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artisan Review',
                'ordering': ['-created_at'],
                'unique_together': {('artisan', 'reviewer')},
            },
        ),
    ]
